#!/bin/bash
set -euo pipefail

if [ "$UID" -lt 1000 ] || [ "$UID" -gt 65533 ]; then
    echo "Error: UID must be between 1000-65533" >&2
    exit 1
fi

if [ "$GID" -lt 1000 ] || [ "$GID" -gt 65533 ]; then
    echo "Error: GID must be between 1000-65533" >&2
    exit 1
fi

if [ "$(id --group proxmark)" -ne "$GID" ]; then
    groupmod --gid "$GID" proxmark
fi

if [ "$(id --user proxmark)" -ne "$UID" ]; then
    usermod --uid "$UID" --gid "$GID" proxmark
fi

if [ ! -f /proxmark/.proxmark3/preferences.json ]; then
    mkdir -p /proxmark/.proxmark3
    cp /root/.proxmark3/preferences.json /proxmark/.proxmark3/
fi

if [ "$(stat -c '%u:%g' /proxmark)" != "${UID}:${GID}" ]; then
    find /proxmark -xdev \( -type d -o -type f \) \
        -exec chown "${UID}:${GID}" {} +
fi

exec gosu proxmark "$@"
